# Tranquilpeak
# Version : 0.5.3-BETA
# Author : Thibaud Leprêtre

baseURL = "https://errolseo.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Errol's AI blog"
theme = "hugo-tranquilpeak-theme"
disqusShortname = "Errol Seo"
# googleAnalytics = "UA-123-45"
paginate = 7
canonifyurls = true

[permalinks]
  posts = "/:year/:month/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"

# ------
# Markup
# ------
[markup]
  # Set startLevel = 1 to support # title (<h1>title</h1>) otherwise table of content is blank/empty
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  [markup.highlight]
    style = 'monokailight'

  
# ------
# Author
# ------
[author]
  name = "Errol Seo"
  bio = "Machine learning research engineer"
  job = "NLP"
  location = "Republic of Korea"
  picture = "images/profile.jpg"

# ------------
# Sidebar menu
# ------------
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-list\" aria-hidden=\"true\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-tags\" aria-hidden=\"true\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 4
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-folder-open\" aria-hidden=\"true\"></i>"
  url = "/archives"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-user\" aria-hidden=\"true\"></i>"
  url = "/about"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\" aria-hidden=\"true\"></i>"
  url = "https://github.com/errolseo"

# -------------
# Customization
# -------------
[params]
  # -----------
  # Description
  # -----------
  description = "Errol's AI blog"

  # -----------
  # Date format
  # -----------
  # Customize date format use to render blog post date, categories and other
  # You must use date format used by Go Time package https://golang.org/pkg/time/
  # Months (not work with short month like "jan", "feb", etc) are translated if translation exists on i18n folders
  # Default format is: January 2, 2006n
  #  dateFormat = "2 January 2006"

  # ---------------------------
  # Posts related configuration
  # ---------------------------
  # Global keywords configuration. Following keywords will be add to every pages
  #  keywords = ["development", "next-gen"]

  # Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
  clearReading = true

  # Define categories will create hierarchy between parents: `categories = ["foo", "bar"]` will consider "bar" a sub-category of "foo".
  # If false it will flat categories.
  hierarchicalCategories = true

  # Display `Next` on left side of the pagination, and `Prev` on right side one.
  # If you set this value to `true`, these positions swap.
  swapPaginator = true

  sidebarBehavior = 2

  # Customize link of author avatar in sidebar
  #  [params.sidebar.profile]
  #    url = "/#about"

  # -------------------
  # Media configuration
  # -------------------
  # Your blog cover picture. I STRONGLY recommend you to use a CDN to speed up loading of pages.
  # There is many free CDN like Cloudinary or you can also use indirectly
  # by using services like Google Photos.
  # Current image is on AWS S3 and delivered by AWS CloudFront.
  # Otherwise put your image, for example `cover.jpg` in folder `static/images/`,
  # and use relative url : `images/cover.jpg`
  coverImage = "images/cover.jpg"
  cover = true

  # Display an image gallery at the end of a post which have photos variables (false: disabled, true: enabled)
  imageGallery = true

  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true

  # Your favicon path, default is "/favicon.png"
  #  favicon = "/favicon.png"
  
  # ---------------
  # Sharing options
  # ---------------
  # Comment and uncomment to enable or disable sharing options
  # If you wanna add a sharing option, read user documentation :
  # Tranquilpeak configuration > Theme configuration > sharing-options
  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fab fa-facebook-square"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"

  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fab fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

  [[params.sharingOptions]]
    name = "Linkedin"
    icon = "fab fa-linkedin"
    url = "https://www.linkedin.com/sharing/share-offsite/?url=%s"


  # --------------------
  # Header configuration
  # --------------------
  # The link at the right of the header is customizable
  # You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
  # By default, author's gravatar or author's picture is displayed.
  #  url: /#search
  #  icon: search
  #  class: st-search-show-outputs
  [params.header.rightLink]
    class = ""
    icon = ""
    url = "/about"
